version: "3.5"

services:
  gve_devnet_sdwan_ups_power_cycle:
    image: ghcr.io/gve-sw/gve_devnet_sdwan_ups_power_cycle:latest
    container_name: gve_devnet_sdwan_ups_power_cycle
    environment:
      - SDWAN_USER=
      - SDWAN_PASS=
      - SDWAN_URL=
      - UPS_USER=
      - UPS_PASS=
    volumes:
      - config.yaml:/app/config.yaml
    restart: "always"
